### ISSUE TITLE
_mockLocalStorage2.default.removeItem is not a function

### ISSUE THREAD

**Issue by Bryze** [letsrock-today/mock-local-storage#12]
I am executing a function

`export function removeLocalData(key)
{
    try {
        localStorage.removeItem(key);
    } catch (err) {
        console.log(err);
    }
}`

I get an error removeItem is not defined. What could be the issue?

**Comment by nikolay-turpitko** [comment]
Hi! I'm afraid you're on you own here. `_mockLocalStorage2` looks suspicious, there is no such a name in the code. Anyway, I have not used this lib for a long time and cannot help. It's here just to save someone a bit of typing. It's unlikely that someone else would stamp on your question and decided to help sooner than you can solve this issue yourself. Anyway, if you succeed with this issue, please put a comment or PR for others who come. Thx!

**Comment by Bryze** [comment]
I got it to work, but I'm unsure if it's a bug or it should be used in that specific way only.
So, the error probably arose because it was mentioned in a test. As soon as it was imported at the compile time of the test, it started working. Probably it was meant to be used at compile time, but the specified documentation didn't make it clear.

Thanks for your time :)
