### ISSUE TITLE
`localStorage is not defined` error on 1.1.0

### ISSUE THREAD

**Issue by dustinsavery** [letsrock-today/mock-local-storage#15]
We just received the `1.1.0` update when running `npm i` this morning, it appears that you are missing a `global.` when setting up local storage and session storage [here](https://github.com/letsrock-today/mock-local-storage/compare/v1.0.5...v1.1.0#diff-dca32a32f3cca28b7b359da8da82bdc5R85). Working on a PR to correct.

**Comment by etaybarzilay89** [comment]
I have the same problem. fixed an older version for now.

**Comment by dustinsavery** [comment]
Fixed by #16
