### ISSUE TITLE
usage with karma?

### ISSUE THREAD

**Issue by surfjedi** [letsrock-today/mock-local-storage#2]
How would you use this with karma for testing angular apps?

**Comment by nikolay-turpitko** [comment]
Well, personally I don't know. We haven't used neither karma nor angular in our projects.
But this is an open source project. Anyone who knows the answer, please feel free to comment here.
You may also try to ask this question on StackOverflow, or address it to Karma team.
If code modification is necessary, PR is welcome, I will merge it.

The chances are, you don't need it for Karma anyway. As I understood from the intro on their website, they execute javascript in the headless browsers, which, should have their own localStorage implementation.

**Comment by nikolay-turpitko** [comment]
Due lack of interest from author of this issue and other users, I'll close it.
@surfjedi feel free to reopen it and comment, if you disagree.
