### ISSUE TITLE
Incompatible API with browser localStorage

### ISSUE THREAD

**Issue by eavichay** [letsrock-today/mock-local-storage#24]
To reproduce: https://gist.github.com/eavichay/9f636bddd202b230a34c7d1d7b550127

The browser's API throws a TypeError when calling `localStorage.setItem` with only one argument.
I am working on some local storage utility, and all the tests have passed, but on runtime, the utility failed.

**Comment by nikolay-turpitko** [comment]
@eavichay I merged your [PR](https://github.com/letsrock-today/mock-local-storage/pull/25), hope this issue is fixed.
