### ISSUE TITLE
Doesn't expose Storage interface

### ISSUE THREAD

**Issue by Munter** [letsrock-today/mock-local-storage#3]
The [storage specification](https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-interface) says `localStorage` and `sessionStorage` are following the `Storage` interface. This mock doesn't expose `Storage` to the global scope.

If some library does a runtime check on `Storage` rather than `localStorage`, the check will fail.

It seems that this mock might just be able to expose the `createStorage` function as `global.Storage`. It's not an interface, but I'm not sure how to make it one

**Comment by nikolay-turpitko** [comment]
Hi! If you really need it here, would you please send a PR, preferably with test? I'll merge it.

**Comment by nikolay-turpitko** [comment]
I need help from the actual users of this project. Personally I haven't used it for some time.
@Munter, @kristianmandrup: guys, you are more competent JS programmers, than I am, could you please help?

**Comment by kristianmandrup** [comment]
I think it is fine as is. No reason to be "invested" in such a small project. Let it be ;)
