### ISSUE TITLE
TypeError: localStorage.getItem is not a function

### ISSUE THREAD

**Issue by warent** [letsrock-today/mock-local-storage#5]
This is surprising. With setItem I would expect getItem as well

**Comment by nikolay-turpitko** [comment]
You are welcome to create a PR.

Honestly, I haven't used this project for couple of years and I'd be glad to transfer ownership of this repo to someone who want to support it. Will you?

**Comment by nikolay-turpitko** [comment]
@kristianmandrup Do you think, that this is related issue to #7 and can be closed now as well?

**Comment by kristianmandrup** [comment]
Yes, all can be closed now. I'm happy. Works for me!

**Comment by nikolay-turpitko** [comment]
Thanks, @kristianmandrup !

@warent I'm closing this issue, because it seems to be fixed. Unfortunately, I have no time to check it myself, feel free to reopen it, if you disagree.
